import type { ProductInput } from '../shared/schemas/product.js';

export type CatalogEntry = Omit<ProductInput, 'nameLower'>;

export const catalog: CatalogEntry[] = [
  {
    name: 'Teclado mecánico RGB Aurora TKL',
    description: 'Teclado mecánico TKL con switches lineales e iluminación RGB por tecla.',
    price: 89999,
    stock: 40,
    category: 'keyboard',
    displayColor: 'lime',
    imageUrl: 'https://placehold.co/600x400?text=Aurora+TKL',
    isActive: true,
    specs: [
      { label: 'Switches', value: 'Lineales rojos' },
      { label: 'Formato', value: 'TKL (87 teclas)' },
      { label: 'Conexión', value: 'USB-C desmontable' },
      { label: 'Iluminación', value: 'RGB por tecla' },
    ],
    curatorialNote:
      'Lo probamos dos semanas escribiendo largo y jugando shooters: los switches lineales no cansan el dedo en sesiones de horas. No es para quien busca el clack táctil de un switch marrón.',
  },
  {
    name: 'Teclado mecánico wireless Nimbus 65%',
    description: 'Teclado compacto 65% con conexión inalámbrica de baja latencia.',
    price: 124999,
    stock: 25,
    category: 'keyboard',
    displayColor: 'magenta',
    imageUrl: 'https://placehold.co/600x400?text=Nimbus+65',
    isActive: true,
    specs: [
      { label: 'Switches', value: 'Táctiles marrones' },
      { label: 'Formato', value: '65% (68 teclas)' },
      { label: 'Conexión', value: 'Bluetooth 5.0 / 2.4GHz' },
      { label: 'Batería', value: 'Hasta 40 horas' },
    ],
    curatorialNote:
      'El formato 65% libera escritorio sin sacrificar las flechas. Quédate con el Vertex si prefieres low-profile; este es para quien quiere el click clásico en un cuerpo chico.',
  },
  {
    name: 'Teclado mecánico low-profile Vertex',
    description: 'Perfil bajo con switches táctiles, ideal para sesiones largas.',
    price: 99999,
    stock: 30,
    category: 'keyboard',
    displayColor: 'cyan',
    imageUrl: 'https://placehold.co/600x400?text=Vertex',
    isActive: true,
    specs: [
      { label: 'Switches', value: 'Táctiles low-profile' },
      { label: 'Formato', value: 'TKL (87 teclas)' },
      { label: 'Conexión', value: 'USB-C' },
      { label: 'Altura', value: '22mm' },
    ],
    curatorialNote:
      'Nueve horas de oficina y después una partida no deberían cansar la muñeca de la misma forma. Este es el que recomendamos para eso, no para quien busca el recorrido largo de un switch tradicional.',
  },
  {
    name: 'Mouse gamer inalámbrico Vector Pro',
    description: 'Sensor óptico de alta precisión y batería de larga duración.',
    price: 54999,
    stock: 60,
    category: 'mouse',
    displayColor: 'amber',
    imageUrl: 'https://placehold.co/600x400?text=Vector+Pro',
    isActive: true,
    specs: [
      { label: 'Sensor', value: 'Óptico 26000 DPI' },
      { label: 'Conexión', value: 'Inalámbrico 2.4GHz' },
      { label: 'Peso', value: '79g' },
      { label: 'Batería', value: 'Hasta 70 horas' },
    ],
    curatorialNote:
      'El peso justo para mover la muñeca, no el brazo entero. Si necesitas doce botones programables para MMO, este no es el tuyo: mira el Titan.',
  },
  {
    name: 'Mouse óptico ultraliviano Comet',
    description: 'Carcasa perforada de menos de 60 gramos para movimientos rápidos.',
    price: 39999,
    stock: 80,
    category: 'mouse',
    displayColor: 'lime',
    imageUrl: 'https://placehold.co/600x400?text=Comet',
    isActive: true,
    specs: [
      { label: 'Sensor', value: 'Óptico 16000 DPI' },
      { label: 'Conexión', value: 'USB con cable' },
      { label: 'Peso', value: '58g' },
      { label: 'Carcasa', value: 'Perforada' },
    ],
    curatorialNote:
      'Menos de 60 gramos porque en un shooter competitivo cada gramo se siente. La carcasa perforada no es para quien juega con las manos sudadas y sin guantes.',
  },
  {
    name: 'Mouse ergonómico Titan MMO',
    description: 'Doce botones programables laterales, pensado para juegos MMO.',
    price: 69999,
    stock: 35,
    category: 'mouse',
    displayColor: 'magenta',
    imageUrl: 'https://placehold.co/600x400?text=Titan+MMO',
    isActive: true,
    specs: [
      { label: 'Sensor', value: 'Óptico 19000 DPI' },
      { label: 'Botones programables', value: '12 laterales' },
      { label: 'Conexión', value: 'USB con cable' },
      { label: 'Peso', value: '132g' },
    ],
    curatorialNote:
      'Doce botones al alcance del pulgar cambian un MMO entero. Es pesado a propósito, para apoyar la mano, no para levantarlo en un flick shot.',
  },
  {
    name: 'Headset gamer 7.1 surround Pulsar',
    description: 'Sonido envolvente virtual 7.1 con micrófono retráctil.',
    price: 79999,
    stock: 45,
    category: 'headset',
    displayColor: 'cyan',
    imageUrl: 'https://placehold.co/600x400?text=Pulsar',
    isActive: true,
    specs: [
      { label: 'Sonido', value: '7.1 virtual' },
      { label: 'Micrófono', value: 'Retráctil con cancelación de ruido' },
      { label: 'Conexión', value: 'USB' },
      { label: 'Almohadillas', value: 'Espuma viscoelástica' },
    ],
    curatorialNote:
      'El surround virtual ayuda de verdad a ubicar pasos en un shooter competitivo. Si buscas algo liviano para usar todo el día, elige el Aether.',
  },
  {
    name: 'Headset inalámbrico Aether Wireless',
    description: 'Conexión 2.4GHz de baja latencia y hasta 20 horas de batería.',
    price: 109999,
    stock: 20,
    category: 'headset',
    displayColor: 'amber',
    imageUrl: 'https://placehold.co/600x400?text=Aether',
    isActive: true,
    specs: [
      { label: 'Sonido', value: 'Estéreo' },
      { label: 'Micrófono', value: 'Desmontable' },
      { label: 'Conexión', value: '2.4GHz de baja latencia' },
      { label: 'Batería', value: 'Hasta 20 horas' },
    ],
    curatorialNote:
      'Sin cables y sin el retardo que arruina el timing en un ritmo. Le falta el surround del Pulsar, y está bien: no todos lo necesitan.',
  },
  {
    name: 'Headset con cancelación de ruido Nova ANC',
    description: 'Cancelación activa de ruido para concentrarse en partidas competitivas.',
    price: 134999,
    stock: 15,
    category: 'headset',
    displayColor: 'lime',
    imageUrl: 'https://placehold.co/600x400?text=Nova+ANC',
    isActive: true,
    specs: [
      { label: 'Sonido', value: 'Estéreo con ANC' },
      { label: 'Micrófono', value: 'Retráctil' },
      { label: 'Conexión', value: 'Bluetooth y USB' },
      { label: 'Batería', value: 'Hasta 25 horas' },
    ],
    curatorialNote:
      'La cancelación activa vale la pena en una casa con ruido. Si tu prioridad es la localización de sonido en competitivo, el Pulsar te va a rendir más.',
  },
  {
    name: 'Monitor gamer 27" 165Hz Horizon',
    description: 'Panel IPS de 27 pulgadas, 165Hz y 1ms de respuesta.',
    price: 349999,
    stock: 12,
    category: 'monitor',
    displayColor: 'magenta',
    imageUrl: 'https://placehold.co/600x400?text=Horizon+27',
    isActive: true,
    specs: [
      { label: 'Panel', value: 'IPS' },
      { label: 'Resolución', value: '2560x1440' },
      { label: 'Refresco', value: '165Hz' },
      { label: 'Respuesta', value: '1ms' },
    ],
    curatorialNote:
      'El punto medio entre color fiel y velocidad. Si tu prioridad es el espacio de pantalla por encima de todo, el Zenith ultrawide te sirve más.',
  },
  {
    name: 'Monitor curvo 34" ultrawide Zenith',
    description: 'Formato ultrawide curvo, ideal para simuladores y productividad.',
    price: 599999,
    stock: 8,
    category: 'monitor',
    displayColor: 'cyan',
    imageUrl: 'https://placehold.co/600x400?text=Zenith+34',
    isActive: true,
    specs: [
      { label: 'Panel', value: 'VA curvo' },
      { label: 'Resolución', value: '3440x1440' },
      { label: 'Refresco', value: '144Hz' },
      { label: 'Curvatura', value: '1500R' },
    ],
    curatorialNote:
      'El ultrawide cambia como se juega un simulador o se trabaja con varias ventanas. No es el que elegiría alguien que solo busca el refresco más alto posible: para eso está el Sprint.',
  },
  {
    name: 'Monitor 24" 144Hz Sprint',
    description: 'Panel de 24 pulgadas orientado a juegos competitivos.',
    price: 229999,
    stock: 18,
    category: 'monitor',
    displayColor: 'amber',
    imageUrl: 'https://placehold.co/600x400?text=Sprint+24',
    isActive: true,
    specs: [
      { label: 'Panel', value: 'TN' },
      { label: 'Resolución', value: '1920x1080' },
      { label: 'Refresco', value: '144Hz' },
      { label: 'Respuesta', value: '1ms' },
    ],
    curatorialNote:
      'Chico y rápido, pensado para quien prioriza cuadros por segundo sobre todo lo demás. Si te importa el color, el Horizon con panel IPS te va a convencer más.',
  },
  {
    name: 'Silla gamer ergonómica Apex',
    description: 'Soporte lumbar ajustable y reposabrazos 4D.',
    price: 189999,
    stock: 10,
    category: 'chair',
    displayColor: 'lime',
    imageUrl: 'https://placehold.co/600x400?text=Apex',
    isActive: true,
    specs: [
      { label: 'Respaldo', value: 'Reclinable 135 grados' },
      { label: 'Soporte lumbar', value: 'Ajustable' },
      { label: 'Reposabrazos', value: '4D' },
      { label: 'Capacidad', value: '120kg' },
    ],
    curatorialNote:
      'El soporte lumbar ajustable es lo que la diferencia después de la tercera hora sentado. La Voyager reclina más si buscas directamente descansar, no trabajar.',
  },
  {
    name: 'Silla gamer reclinable Voyager',
    description: 'Reclinación de hasta 165 grados con reposapiés integrado.',
    price: 219999,
    stock: 7,
    category: 'chair',
    displayColor: 'magenta',
    imageUrl: 'https://placehold.co/600x400?text=Voyager',
    isActive: true,
    specs: [
      { label: 'Respaldo', value: 'Reclinable 165 grados' },
      { label: 'Reposapiés', value: 'Integrado' },
      { label: 'Reposabrazos', value: '3D' },
      { label: 'Capacidad', value: '130kg' },
    ],
    curatorialNote:
      'Reclina casi horizontal con reposapiés propio, para el que quiere una siesta entre partidas. No es la más firme para escribir largo: ahí la Apex rinde mejor.',
  },
  {
    name: 'Silla gamer compacta Drift',
    description: 'Diseño compacto pensado para escritorios chicos.',
    price: 149999,
    stock: 14,
    category: 'chair',
    displayColor: 'cyan',
    imageUrl: 'https://placehold.co/600x400?text=Drift',
    isActive: true,
    specs: [
      { label: 'Respaldo', value: 'Reclinable 120 grados' },
      { label: 'Ancho de asiento', value: 'Reducido' },
      { label: 'Reposabrazos', value: 'Fijos' },
      { label: 'Capacidad', value: '100kg' },
    ],
    curatorialNote:
      'Pensada para escritorios chicos donde una silla gamer tradicional no entra. Sacrifica reclinación y reposabrazos ajustables para lograrlo.',
  },
  {
    name: 'Mousepad XL Cosmos',
    description: 'Superficie extendida de tela para mouse y teclado.',
    price: 14999,
    stock: 100,
    category: 'mousepad',
    displayColor: 'amber',
    imageUrl: 'https://placehold.co/600x400?text=Cosmos',
    isActive: true,
    specs: [
      { label: 'Superficie', value: 'Tela de baja fricción' },
      { label: 'Tamaño', value: '900x400mm' },
      { label: 'Base', value: 'Goma antideslizante' },
      { label: 'Borde', value: 'Sin costura' },
    ],
    curatorialNote:
      'El tamaño XL cubre teclado y mouse en la misma superficie, para quien juega con sensibilidad baja y barre mucho. Si tu escritorio es chico, el Ridge te alcanza.',
  },
  {
    name: 'Mousepad de tela con borde cosido Ridge',
    description: 'Base de goma antideslizante y bordes cosidos.',
    price: 9999,
    stock: 120,
    category: 'mousepad',
    displayColor: 'lime',
    imageUrl: 'https://placehold.co/600x400?text=Ridge',
    isActive: true,
    specs: [
      { label: 'Superficie', value: 'Tela de fricción media' },
      { label: 'Tamaño', value: '450x400mm' },
      { label: 'Base', value: 'Goma antideslizante' },
      { label: 'Borde', value: 'Cosido' },
    ],
    curatorialNote:
      'El tamaño estándar para quien no necesita barrer medio escritorio. El borde cosido evita que se deshilache con el uso diario.',
  },
  {
    name: 'Mousepad con carga inalámbrica PowerPad',
    description: 'Carga inalámbrica integrada para mouse compatibles.',
    price: 29999,
    stock: 40,
    category: 'mousepad',
    displayColor: 'magenta',
    imageUrl: 'https://placehold.co/600x400?text=PowerPad',
    isActive: true,
    specs: [
      { label: 'Superficie', value: 'Tela de fricción media' },
      { label: 'Tamaño', value: '350x250mm' },
      { label: 'Carga inalámbrica', value: '10W Qi' },
      { label: 'Cable', value: 'USB-C' },
    ],
    curatorialNote:
      'Resuelve el mouse inalámbrico que siempre se queda sin batería a mitad de partida. Es chico a propósito: no compite con el Cosmos en superficie de juego.',
  },
];
