#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

banner "CLACK · infraestructura (Firebase, AWS S3, Vercel)"

# ── vercel_env: agrega una variable a Production Y Preview en Vercel ──────
# No es parte de la libreria del wizard (eso no se toca); es un helper propio
# de este script, mismo estilo que set_secret/set_var de arriba.
vercel_env() {
  local name="$1" value="$2" ok=1
  if ! command -v vercel >/dev/null 2>&1; then
    SKIPPED+=("Vercel env $name (CLI no encontrado)")
    warn "vercel no esta instalado; seteala a mano despues"
    return
  fi
  if printf '%s' "$value" | vercel env add "$name" production >/dev/null 2>&1; then
    :
  else
    ok=0
  fi
  if printf '%s' "$value" | vercel env add "$name" preview >/dev/null 2>&1; then
    :
  else
    ok=0
  fi
  if [[ "$ok" -eq 1 ]]; then
    printf '  %s✓ Vercel%s %s en Production + Preview\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel env $name (ya existia, o fallo: seteala a mano en el dashboard)")
    warn "$name puede no haberse seteado en una de las dos; revisa el dashboard"
  fi
}

# ═══════════════════════════════════════════════════════════════════════
# FIREBASE
# ═══════════════════════════════════════════════════════════════════════

stage "Firebase: crear el proyecto"
say "Vamos a crear el proyecto de Firebase que va a servir Authentication y"
say "Firestore para CLACK."
open_url "https://console.firebase.google.com/"
step "Click en 'Agregar proyecto' / 'Add project'."
step "Nombre sugerido: clack (o el que prefieras)."
step "Si te pregunta por Google Analytics, podes desactivarlo: no lo usamos."
step "Click en 'Crear proyecto' y esperá a que termine."
say ""
say "Una vez creado, el ID del proyecto aparece en la URL de la consola"
say "(algo como clack-a1b2c) y tambien en el engranaje > Configuracion del"
say "proyecto > General, campo 'ID de proyecto'."
ask FIREBASE_PROJECT_ID "ID del proyecto de Firebase:"
write_env VITE_FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
write_env FIREBASE_ADMIN_PROJECT_ID "$FIREBASE_PROJECT_ID"
note "el ID de proyecto es el mismo valor para VITE_FIREBASE_PROJECT_ID y"
note "para FIREBASE_ADMIN_PROJECT_ID: ya quedaron los dos escritos."

stage "Firebase: Authentication (Email/Password + Google)"
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/authentication/providers"
step "Si es la primera vez, click en 'Comenzar' / 'Get started'."
step "En la lista de proveedores, abri 'Correo electronico/contraseña',"
step "activa el interruptor y Guardar."
step "Abri 'Google' y activalo. Se abre un paso 2 de 2 con dos campos:"
step "'Nombre publico del proyecto': viene autocompletado con algo como"
step "'project-123456789', que es el numero interno del proyecto. Cambialo"
step "a CLACK: es lo que un usuario ve en la pantalla de Google al iniciar"
step "sesion ('Continuar a CLACK'), y dejarlo con el numero se ve roto."
step "'Correo electronico de asistencia del proyecto': el desplegable te"
step "muestra tu propia cuenta de Google: dejala como esta."
step "Las secciones colapsables de abajo (entidades seguras, SDK web) son"
step "para casos avanzados: no hace falta abrirlas."
step "Guardar."
say ""
warn "no hace falta ninguna otra configuracion aca: la app va a usar estos"
warn "dos metodos y ninguno mas."
confirm "Los dos proveedores quedaron activados?" || warn "segui cuando esten listos, podes volver a correr el wizard"

stage "Firebase: Firestore (modo produccion)"
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/firestore"
step "Click en 'Crear base de datos' / 'Create database'."
step "Elegi modo PRODUCCION (Production mode), NO modo de prueba."
note "modo produccion arranca con todo cerrado por defecto, que es"
note "exactamente lo que el proyecto necesita: las security rules se"
note "escriben en el andamiaje, nunca queda todo abierto ni un dia."
step "Elegi la ubicacion. Sugerido para Argentina: southamerica-east1"
step "(Sao Paulo). Confirmá: la ubicación NO se puede cambiar despues."
step "Click en 'Habilitar' / 'Enable' y esperá a que termine."
confirm "Firestore quedo creado en modo produccion?" || warn "segui cuando este listo"

stage "Firebase: configuracion de la app web"
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/settings/general"
step "Baja hasta 'Tus apps' / 'Your apps'."
step "Si no hay ninguna app web, click en el icono </> para agregar una."
step "Nombre sugerido: clack-web. NO marques 'Tambien configura Firebase"
step "Hosting': el deploy va por Vercel, no por Firebase Hosting."
step "Copia los valores del objeto firebaseConfig que te muestra:"
say "    apiKey, authDomain, appId"
ask FIREBASE_API_KEY "apiKey:"
ask FIREBASE_AUTH_DOMAIN "authDomain (ej: clack-xxxxx.firebaseapp.com):"
ask FIREBASE_APP_ID "appId:"
write_env VITE_FIREBASE_API_KEY "$FIREBASE_API_KEY"
write_env VITE_FIREBASE_AUTH_DOMAIN "$FIREBASE_AUTH_DOMAIN"
write_env VITE_FIREBASE_APP_ID "$FIREBASE_APP_ID"
write_env VITE_USE_FIREBASE_EMULATORS "true"
note "VITE_USE_FIREBASE_EMULATORS quedo en true: en tu maquina local el"
note "cliente habla con el Emulator Suite, no con el proyecto real."

stage "Firebase: clave del Admin SDK"
say "Esta clave es la que usan las Vercel Functions para verificar tokens"
say "y asignar el rol de admin. Es un secreto real: nunca va al repositorio."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/settings/serviceaccounts/adminsdk"
step "Click en 'Generar nueva clave privada' / 'Generate new private key'."
step "Confirma. Se descarga un archivo .json a tu carpeta de Descargas."
warn "ese archivo .json es una credencial completa. No lo copies dentro de"
warn "la carpeta del proyecto, y borralo de Descargas apenas termines aca."
say ""
step "Abri el .json descargado con un editor de texto."
step "Copia el valor del campo \"client_email\" (sin las comillas)."
ask FIREBASE_ADMIN_CLIENT_EMAIL "client_email:"
say ""
step "Copia el valor del campo \"private_key\" COMPLETO, tal cual aparece"
step "en el archivo: con las comillas afuera pero sin sacarlas, y con los"
step "\\n literales adentro (NO son saltos de linea reales en el archivo"
step "de texto: son la secuencia de dos caracteres barra-ene)."
note "el codigo hace .replace(/\\\\n/g, '\\n') al inicializar, asi que espera"
note "exactamente ese formato. Pegar la clave ya con saltos de linea reales"
note "es el error mas comun de este paso y el mensaje que da no ayuda nada."
ask_secret FIREBASE_ADMIN_PRIVATE_KEY "private_key completo (una sola linea, con los \\n literales):"
write_env FIREBASE_ADMIN_CLIENT_EMAIL "$FIREBASE_ADMIN_CLIENT_EMAIL"
write_env FIREBASE_ADMIN_PRIVATE_KEY "$FIREBASE_ADMIN_PRIVATE_KEY"
say ""
warn "borra ahora el .json descargado de tu carpeta de Descargas: ya"
warn "copiaste los dos campos que hacen falta."
confirm "Borraste el archivo .json descargado?" || warn "borralo antes de seguir"

# ═══════════════════════════════════════════════════════════════════════
# AWS S3
# ═══════════════════════════════════════════════════════════════════════

stage "AWS S3: crear el bucket"
open_url "https://s3.console.aws.amazon.com/s3/bucket/create"
step "Nombre del bucket: tiene que ser unico a nivel mundial. Sugerido:"
step "clack-product-images-<algo-random-tuyo>, ej clack-product-images-47x9."
ask S3_BUCKET "Nombre del bucket que elegiste:"
step "Elegi la region (ej us-east-1)."
ask S3_REGION "Region elegida (ej us-east-1):"
say ""
say "Ahora la parte que importa: 'Block Public Access settings for this"
say "bucket'. Por defecto vienen los 4 checkboxes marcados. Dejalos asi"
say "EXCEPTO estos dos, que hay que DESMARCAR:"
step "'Block public access to buckets and objects granted through new"
step "  public bucket or access point policies' -> DESMARCAR"
step "'Block public access to buckets and objects granted through any"
step "  public bucket or access point policies' -> DESMARCAR"
note "los otros dos (los que hablan de ACLs) quedan MARCADOS: no usamos"
note "ACLs en ningun lado, y bloquearlas no afecta a la bucket policy que"
note "vamos a poner en el proximo stage. Esta es la diferencia entre"
note "'este bucket puede tener una politica publica' (lo que queremos) y"
note "'cualquiera puede escribir ACLs publicas' (lo que NO queremos)."
step "Tildá el checkbox de advertencia y click en 'Crear bucket'."
write_env S3_BUCKET "$S3_BUCKET"
write_env S3_REGION "$S3_REGION"
confirm "El bucket quedo creado con solo esos 2 checkboxes desmarcados?" || warn "revisa el Block Public Access antes de seguir, es la parte sensible"

stage "AWS S3: bucket policy y CORS"
say "Abri el bucket '${S3_BUCKET}' y anda a la pestaña 'Permissions'."
open_url "https://s3.console.aws.amazon.com/s3/buckets/${S3_BUCKET}?tab=permissions"
say ""
say "En 'Bucket policy', click en Edit y pega este JSON exacto"
say "(ya tiene tu nombre de bucket adentro):"
say ""
cat <<BUCKETPOLICY
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadProductImages",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::${S3_BUCKET}/products/*"
        }
    ]
}
BUCKETPOLICY
say ""
note "esto da lectura publica SOLO a lo que este bajo el prefijo products/"
note "del bucket, que es donde las Vercel Functions van a guardar las"
note "imagenes de producto. Nada mas del bucket queda publico."
step "Guardá / 'Save changes'."
confirm "Pegaste la bucket policy y la guardaste?" || warn "volve cuando este lista"
say ""
say "Ahora bajá hasta 'Cross-origin resource sharing (CORS)', click Edit,"
say "y pegá este JSON:"
say ""
cat <<CORSPOLICY
[
    {
        "AllowedHeaders": ["*"],
        "AllowedMethods": ["PUT", "GET"],
        "AllowedOrigins": [
            "http://localhost:5173",
            "https://*.vercel.app"
        ],
        "ExposeHeaders": ["ETag"],
        "MaxAgeSeconds": 3000
    }
]
CORSPOLICY
say ""
note "localhost:5173 es el puerto por defecto de Vite en desarrollo."
note "https://*.vercel.app cubre tanto el dominio de produccion como"
note "cada preview de rama (Vercel solo permite un * por origen, por eso"
note "no se puede ser mas especifico todavia). Si mas adelante agregas un"
note "dominio propio, hay que sumarlo aca."
step "Guardá."
confirm "Pegaste el CORS y lo guardaste?" || warn "volve cuando este listo"

stage "AWS IAM: usuario de permisos minimos"
say "Este usuario es el que la Vercel Function usa para FIRMAR las URLs de"
say "subida. Sus credenciales van a Vercel, nunca al navegador."
open_url "https://console.aws.amazon.com/iam/home#/users"
step "Click 'Create user' / 'Crear usuario'."
step "Nombre: clack-s3-uploader (o el que prefieras)."
step "NO tildes 'Provide user access to the AWS Management Console':"
step "este usuario es solo programatico, nunca va a loguearse a la consola."
step "Next."
step "En permisos, elegi 'Attach policies directly'."
step "Click en 'Create policy' (abre una pestaña nueva)."
say ""
say "En el editor de la policy nueva, pestaña JSON, pega esto"
say "(ya tiene tu bucket adentro):"
say ""
cat <<IAMPOLICY
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowPresignedUploadsToProductsPrefix",
            "Effect": "Allow",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::${S3_BUCKET}/products/*"
        }
    ]
}
IAMPOLICY
say ""
note "solo s3:PutObject, solo sobre products/*. Nada de ListBucket, nada"
note "de GetObject: ese usuario no necesita leer nada, solo escribir ahi."
step "Nombre de la policy: ClackS3UploadPolicy. Crear policy."
step "Volve a la pestaña del usuario, refresca la lista, busca"
step "'ClackS3UploadPolicy', selecciónala, Next, 'Create user'."
say ""
step "Entra al usuario recien creado > pestaña 'Security credentials'."
step "Baja hasta 'Access keys', click 'Create access key'."
step "Elegi el caso de uso que corresponda a una app fuera de AWS"
step "(el texto exacto puede variar segun la version de la consola:"
step "'Application running outside AWS' o 'Third-party service')."
step "Next, Create access key."
warn "la Secret access key se muestra UNA SOLA VEZ. Si la perdes, hay que"
warn "generar una nueva desde cero."
ask S3_ACCESS_KEY_ID "Access key ID:"
ask_secret S3_SECRET_ACCESS_KEY "Secret access key:"
write_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
write_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"

# ═══════════════════════════════════════════════════════════════════════
# VERCEL
# ═══════════════════════════════════════════════════════════════════════

stage "Vercel: crear y linkear el proyecto"
say "Vamos a crear el proyecto con el CLI en vez del dashboard, para no"
say "disparar un deploy automatico todavia: no hay package.json, asi que"
say "cualquier deploy ahora fallaria sin que eso signifique nada malo."
say ""
if ! command -v vercel >/dev/null 2>&1; then
  warn "no se encontro el comando 'vercel'. Instalalo con: npm i -g vercel"
  SKIPPED+=("vercel CLI no instalado: correr este stage a mano despues")
else
  if ! vercel whoami >/dev/null 2>&1; then
    step "No hay sesion de Vercel CLI activa. Se va a abrir el login."
    pause "Presiona Enter para correr 'vercel login'..."
    vercel login || warn "el login no se completo; volve a correr el wizard"
  fi
  step "Ahora corre 'vercel link'. Te va a preguntar equipo/scope y si"
  step "queres crear un proyecto nuevo: decile que si, nombre 'clack'."
  pause "Presiona Enter para correr 'vercel link'..."
  vercel link || warn "el link no se completo; volve a correr este stage"
fi

stage "Vercel: cargar las variables de entorno"
say "Con el proyecto ya linkeado, subimos todo lo que juntamos hasta"
say "ahora a Production Y Preview. Firestore/AWS reales se comparten"
say "entre los dos, no hay un proyecto de staging aparte."
say ""
note "VITE_USE_FIREBASE_EMULATORS NO se sube: en Vercel esa variable no"
note "existe, y sin ella el cliente habla con el proyecto real de Firebase."
vercel_env "VITE_FIREBASE_API_KEY" "$FIREBASE_API_KEY"
vercel_env "VITE_FIREBASE_AUTH_DOMAIN" "$FIREBASE_AUTH_DOMAIN"
vercel_env "VITE_FIREBASE_PROJECT_ID" "$FIREBASE_PROJECT_ID"
vercel_env "VITE_FIREBASE_APP_ID" "$FIREBASE_APP_ID"
vercel_env "FIREBASE_ADMIN_PROJECT_ID" "$FIREBASE_PROJECT_ID"
vercel_env "FIREBASE_ADMIN_CLIENT_EMAIL" "$FIREBASE_ADMIN_CLIENT_EMAIL"
vercel_env "FIREBASE_ADMIN_PRIVATE_KEY" "$FIREBASE_ADMIN_PRIVATE_KEY"
vercel_env "S3_REGION" "$S3_REGION"
vercel_env "S3_BUCKET" "$S3_BUCKET"
vercel_env "S3_ACCESS_KEY_ID" "$S3_ACCESS_KEY_ID"
vercel_env "S3_SECRET_ACCESS_KEY" "$S3_SECRET_ACCESS_KEY"
say ""
note "si alguna salio en amarillo arriba (ya existia de una corrida"
note "anterior), anda al dashboard y confirma el valor a mano:"
note "Project Settings > Environment Variables."

stage "Vercel: conectar el repositorio de GitHub"
say "Ultimo paso: conectar el proyecto a GitHub para que cada push dispare"
say "un preview y cada merge a main despliegue a produccion."
open_url "https://vercel.com/dashboard"
step "Entra al proyecto 'clack' que acabamos de crear."
step "Settings > Git > Connect Git Repository."
step "Seleccioná HRamiroAlbornoz/e-commerce-platform."
warn "al conectar el repo, Vercel puede disparar un deploy automatico ya"
warn "mismo. Como todavia no hay package.json, ese deploy va a FALLAR, y"
warn "eso es lo esperado: no es el deploy de humo real. Ese llega en el"
warn "proximo paso del andamiaje, cuando exista codigo minimo que buildear."
confirm "Conectaste el repositorio?" || warn "volve a este stage cuando lo conectes"

finish
say "Listo. Los valores de Firebase y AWS quedaron en .env (nunca se sube:"
say "esta en .gitignore) y en Vercel (Production + Preview)."
say ""
say "Lo que sigue es el paso 1 del andamiaje: el deploy de humo. Se hace"
say "cuando exista un package.json minimo con /api/health."
